ansible_user: root
ansible_ssh_private_key_file: /home/vlad/.ssh/id_ed25519
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
kubectl:
  user: root
  group: root
docker_users:
  - root
metallb_setup: true
openstack_provider_gateway_setup: true
client_cluster_ssh_setup: true
client_ssh_user: root
cluster_ssh_user: root
calico_setup: true
cilium_setup: false
flannel_setup: false
kubeadm:
  pod_network_cidr: "10.244.0.0/16"
  service_cidr: "10.96.0.0/16"

kube_version_repo: "v1.30"
kube_version: "1.30.3-1.1"
helm_version: "v3.15.3"
crictl_version: "v1.30.1"
calico_version: "v3.27.4"
