#!/bin/bash

export OPENSTACK_RELEASE=2024.1
export HEAT_DIR="$(readlink -f .)"
export SSH_DIR="${HOME}/.ssh"

if [[ -n ${HEAT_DIR} ]]; then
  OPENSTACK_CLIENT_CONTAINER_EXTRA_ARGS="${OPENSTACK_CLIENT_CONTAINER_EXTRA_ARGS} -v ${HEAT_DIR}:${HEAT_DIR}"
fi

if [[ -n ${SSH_DIR} ]]; then
  OPENSTACK_CLIENT_CONTAINER_EXTRA_ARGS="${OPENSTACK_CLIENT_CONTAINER_EXTRA_ARGS} -v ${SSH_DIR}:${SSH_DIR}"
fi

export OPENSTACK_CLIENT_CONTAINER_EXTRA_ARGS

export PUB_NET_NAME="public"
export PUB_SUBNET_NAME="public-subnet"
export PUB_SUBNET="172.24.4.0/24"
export PUB_BR_EX_ADDR="172.24.4.1/24"
export PUB_ALLOCATION_POOL_START="172.24.4.10"
export PUB_ALLOCATION_POOL_END="172.24.4.254"

export PRIVATE_SUBNET_POOL="10.0.0.0/8"
export PRIVATE_SUBNET_POOL_NAME="shared-default-subnetpool"
export PRIVATE_SUBNET_POOL_DEF_PREFIX="24"

export VM_KEY_STACK="heat-vm-key"
export PRIVATE_SUBNET="10.0.0.0/24"
